# Generated by Django 4.2.27 on 2025-12-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Image')),
                ('rating_count', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user_job_title', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
    ]
