# Generated by Django 4.2.27 on 2025-12-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('message', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
