# Generated by Django 4.2.27 on 2026-01-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='error',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
